version: '3.8'

services:
  dash-app:
    build: .
    container_name: sas-copilot
    ports:
      - "8050:8050"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_ENV=production
    volumes:
      - .:/app
    restart: always
